project_id = "uegwrzcdqtienarttczr"

[functions.send-approval-emails]
verify_jwt = false

[functions.invite-member]
verify_jwt = false

[functions.transfer-ownership]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.send-paamindelser]
verify_jwt = false
